# Generated by Django 5.0.4 on 2024-05-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_role',
            field=models.IntegerField(null=True),
        ),
    ]
