# Generated by Django 5.0.4 on 2024-05-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_child_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
