# Generated by Django 5.0.6 on 2024-06-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_child_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
