# Generated by Django 5.0.6 on 2024-07-10 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codeokpo', models.IntegerField(null=True)),
                ('Addokpo', models.IntegerField(null=True)),
                ('Coderjn', models.IntegerField(null=True)),
                ('codved', models.IntegerField(null=True)),
                ('Nokpo', models.CharField(max_length=254, null=True)),
                ('LeverOrg', models.IntegerField(null=True)),
                ('prHosp', models.IntegerField(null=True)),
                ('Address', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='medical_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.medicalinstitution'),
        ),
        migrations.AddField(
            model_name='test',
            name='medical_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_institution_tests', to='main.medicalinstitution'),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.medicalinstitution'),
        ),
    ]
