# Generated by Django 5.0.6 on 2024-07-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_medicalinstitution_child_medical_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalinstitution',
            name='unp',
            field=models.IntegerField(null=True),
        ),
    ]
