# Generated by Django 5.0.6 on 2024-07-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_medicalinstitution_unp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinstitution',
            name='Coderjn',
            field=models.BigIntegerField(null=True),
        ),
    ]
